Backend almost done
4xxi/caesarapp-old-server pull request #4
Opened 2017-08-28 10:18 UTC by Metalrex100

2017-08-28 12:23 UTC, etomilin requested changes

2017-08-28 12:23 UTC, etomilin commented on .php_cs.cache
> +{"php":"7.1.7-1+ubuntu16.04.1+deb.sury.org+1","version":"2.5.0:v2.5.0#63aad575ec2a29d50eb6c3b5cbc17430b28895b2","rules":{"binary_operator_spaces":{"align_double_arrow":false,"align_equals":false},"bl
Добавь этот файл в .gitignore

2017-08-28 12:23 UTC, etomilin commented on app/AppKernel.php
> +            new Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle(),
Для Mongo он не нужен

2017-08-28 12:23 UTC, etomilin commented on composer.json
> +        "doctrine/doctrine-migrations-bundle": "^1.0",
Для Mongo он не нужен

2017-08-28 12:23 UTC, etomilin commented on src/AppBundle/DataProvider/MessageItemDataProvider.php
> + * Created by PhpStorm.
Лучше убери этот шаблон из настроек шторма.

2017-08-28 12:23 UTC, etomilin commented on src/AppBundle/DataProvider/MessageItemDataProvider.php
> +    private $dm;
нужно док-блок

2017-08-28 12:23 UTC, etomilin commented on src/AppBundle/DataProvider/MessageItemDataProvider.php
> +        $message = $this->dm->getRepository('AppBundle:Message')->findOneBy(['id' => $id]);
AppBundle:Message лучше заменить на Message::class - так в будущем будет проще использовать места использования класса

2017-08-28 12:23 UTC, etomilin commented on src/AppBundle/Document/Message.php
> + * @ApiResource
При наличии resources.yml эта аннотация уже не нужна

2017-08-28 12:23 UTC, etomilin commented on src/AppBundle/Document/Message.php
> +     * @param date $expires
DateTime

2017-08-28 12:23 UTC, etomilin commented on src/AppBundle/Document/Message.php
> +     * @return date $expires
DateTime

2017-08-28 12:23 UTC, etomilin commented on src/AppBundle/Document/Message.php
> +     * @Assert\NotBlank()
Нужно дать возможность задавать null для случаев, когда не требуется контроль количества доступов

2017-08-28 12:23 UTC, etomilin commented on src/AppBundle/Document/Message.php
> +     * @MongoDB\Id(strategy="UUID", type="string")
ко всем полям надо добавить док-блок с типом поля

2017-08-28 12:23 UTC, etomilin commented on src/AppBundle/Document/Message.php~
> +<?php
Этого файла не должно быть в гите

2017-08-28 12:23 UTC, etomilin commented on src/AppBundle/EventSubscriber/MessageSubscriber.php
> +            KernelEvents::REQUEST => [['storeEncryptedMessage', EventPriorities::PRE_VALIDATE]],
А почему не PRE_WRITE?

2017-08-29 08:57 UTC, Metalrex100 commented on src/AppBundle/Document/Message.php
> +     * @MongoDB\Id(strategy="UUID", type="string")
Тип поля указывать через `@var type $variable` ?

2017-08-29 09:10 UTC, Metalrex100 commented on src/AppBundle/DataProvider/MessageItemDataProvider.php
> +        $message = $this->dm->getRepository('AppBundle:Message')->findOneBy(['id' => $id]);
При замене на `Message::class` появляется ошибка:
```Unknown Document namespace alias 'Message'```

2017-08-29 10:12 UTC, etomilin commented on src/AppBundle/Document/Message.php
> +     * @MongoDB\Id(strategy="UUID", type="string")
в случае когда аннотация перед единичным полем  достаточно `@var type`

2017-08-30 11:14 UTC, etomilin requested changes

2017-08-30 11:14 UTC, etomilin commented on src/AppBundle/Document/Message.php
> +     * @MongoDB\Field(type="int")
Это можно в базу не писать

2017-08-30 11:14 UTC, etomilin commented on .php_cs.cache
> +{"php":"7.1.7-1+ubuntu16.04.1+deb.sury.org+1","version":"2.5.0:v2.5.0#63aad575ec2a29d50eb6c3b5cbc17430b28895b2","rules":{"binary_operator_spaces":{"align_double_arrow":false,"align_equals":false},"bl
Файл нужно убрать из репозитория

2017-08-30 11:14 UTC, etomilin commented on .gitignore
> +.php_cs.cache
Дубль

2017-08-30 11:14 UTC, etomilin commented on app/AppKernel.php
> +            new \AppBundle\AppBundle(),
А зачем начальный / ?

2017-08-30 11:14 UTC, etomilin commented on app/config/config_dev.yml
> +        strict_requirements: null
А зачем?

2017-08-30 11:14 UTC, etomilin commented on app/config/services.yml
> +            class: 'AppBundle\DataProvider\MessageItemDataProvider'
Отступы лучше выровнять по аналогии с контентом выше

2017-08-30 11:14 UTC, etomilin commented on src/AppBundle/DataProvider/MessageItemDataProvider.php
> +    private $dm;
var аннотация нужна

2017-08-30 11:17 UTC, Metalrex100 commented on app/config/config_dev.yml
> +        strict_requirements: null
Без этого ошибка вылезает в MessageDateProvider

2017-08-30 11:20 UTC, etomilin commented on app/config/config_dev.yml
> +        strict_requirements: null
а что за ошибка? отключение strict_requirements скрывает ошибки валидации урлов, что само по себе не очень хорошо

2017-08-30 11:30 UTC, Metalrex100 commented on app/config/config_dev.yml
> +        strict_requirements: null
```Parameter "id" for route "api_messages_get_item" must match "[^/\.]++" ("" given) to generate a corresponding URL.```

2017-08-30 11:39 UTC, etomilin approved these changes

2017-08-30 11:40 UTC, merged